version: '3.9'
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_USER: shiner
      POSTGRES_PASSWORD: shine-dev-password
      POSTGRES_DB: shine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: